import Image from "next/image"

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

const Aboutpage = () => {
  return (
    <div className='p-12 text-sky-950 font-mono mb-8'>
      <div className=' flex flex-wrap justify-between px-8 py-4'>
        <div className='w-2/3 flex flex-col justify-between px-16'>
          <h2 className="text-3xl font-bold font-mono  text-gray-600">About Agency</h2>
          <h1 className='text-5xl mt-10 font-bold px-6'>We create digital ideas that are bigger, bolder,braver and better</h1>
          <p className='mt-10 text-lg px-6 text-gray-600'>We create digital ideas that are bigger, bolder,braver and better.We believe in good ideas flexibility and precision.We&apos;re world&apos;s Our Special team best consulting & finance solution provider.Wide range of web and software development services.</p>
          <div className='flex flex-wrap gap-20 my-8'>
            <div className="flex flex-col flex-wrap">
              <h2 className="font-bold text-3xl ">10K+</h2>
              <p className="text-gray-600">Year Of experience</p>
            </div>
            <div className="flex flex-col flex-wrap">
              <h2 className="font-bold text-3xl ">234K+</h2>
              <p className="text-gray-600">People reached</p>
            </div>
            <div className="flex flex-col flex-wrap">
              <h2 className="font-bold text-3xl ">5K+</h2>
              <p className="text-gray-600">Services and plugins</p>
            </div>
          </div>
        </div>
        {/* image here */}
        <div className=' flex justify-between p-4 '>
          <Image src='/about.png' alt='about.png' width={400} height={400} />
        </div>
      </div>
    </div>
  )
}

export default Aboutpage