import Footer from "@/Components/Footer";
import Nav from "@/Components/Nav/Nav";
import '@/app/global.css';

export const metadata = {
  title: {
    default: "Blog App",
    template: "%s | Blog App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen overflow-x-hidden min-h-screen">
        <Nav/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
