import Postcard from "@/Components/Postcard/postcard"
import { getPosts } from "@/lib/data"

export const metadata = {
  title: "POSTS",
  description: "Generated by create next app",
};

const Blogpage = async () => {
  // const posts=async()=>{
  //   const res=await fetch('https://jsonplaceholder.typicode.com/posts')
  //   if(!res.ok){
  //     throw new Error(res.statusText)
  //   }
  //   return res.json()
  // }
  const data=await getPosts();
  return (
    <div className="text-gray-600">
      <div className="w-3/4 flex flex-wrap mx-auto gap-4 justify-center mt-20">
        {data.map((post)=>(
          <Postcard key={post.id} post={post}/>
        ))}
      </div>
    </div>
  )
}

export default Blogpage;