import Image from "next/image"

export const metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

const ContactPage = () => {
  return (
    <div className='px-28 py-12 text-sky-950 font-mono mb-20'>
      <div className=' flex flex-wrap justify-between px-8 py-4'>
        <div className=' flex justify-between p-4 '>
          <Image src="/contact.png" alt="contact" width={400} height={400} />
        </div>
        <div className='w-1/2 flex flex-col justify-between px-16'>
          <h2 className='text-3xl font-bold font-mono  text-gray-600'>Contact Us</h2>
          <form className='mt-10 flex flex-col gap-3 w-full'>
            <input type='text' placeholder='Name' className='border-2 p-2 rounded-md min-w-fit ' />
            <input type='email' placeholder='Email' className='border-2 p-2 rounded-md min-w-fit' />
            <input type='text' placeholder='Subject' className='border-2 p-2 rounded-md min-w-fit' />
            <textarea placeholder='Message' className='border-2 p-2 rounded-md  h-40 min-w-fit'></textarea>
            <button className='bg-[#00ABE4] p-2 border-2 rounded-md hover:bg-[#00abe458] transition-all duration-150 min-w-fit'>Send</button>
          </form>
        </div>
      </div>
    </div>
  )
}

export default ContactPage